# Generated by Django 4.0.3 on 2022-03-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='FileConverter',
        ),
    ]
